services:
  server:
    build: server
    ports:
      - 127.0.0.1:${SERVER_FORWARD_PORT:-3050}:3050
    env_file:
      - server/.env
    volumes:
      - ./keys:/keys
      - local-data:/data
    
  redis:
    image: redis:8.0-alpine
    command: >
      --appendonly yes
      --aof-use-rdb-preamble yes
      --maxmemory 256mb
    volumes:
      - redis-data:/data
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"

volumes:
  redis-data: {}
  local-data: {}