services:
  server:
    build: server
    volumes:
      - ./keys:/keys
    ports: []
    env_file:
      - server/.env

  caddy:
    image: caddy:2.8-alpine
    depends_on:
      - server
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env

volumes:
  caddy_data: {}
  caddy_config: {}