services:
  worker:
    build: worker
    volumes:
      - ./keys:/keys
    ports:
      - 127.0.0.1:${WORKER_FORWARD_PORT:3050}:3050
    env_file:
      - worker/.env
    
  # TODO: Implement zip queue instead of zipping on demand!
  # redis:
  #   image: redis:8.0-alpine
  #   command: >
  #     --appendonly no                # locks vanish on restart
  #     --save ""                      # disable RDB snapshots
  #     --requirepass "${REDIS_PASSWORD}"
  #     --maxmemory 128mb              # plenty for a few hundred locks
  #     --maxmemory-policy allkeys-lru
  #   restart: unless-stopped
  #   ports:
  #     - "127.0.0.1:6379:6379"